name: google_maps_cluster_manager_2
description: Simple Flutter clustering library for Google Maps based on Geohash.
version: 3.1.0
homepage: https://github.com/SebastianKlaiber/google_maps_cluster_manager

environment:
  sdk: '>=3.1.5'

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter_platform_interface: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

topics:
  - google-maps
  - google-maps-flutter
  - map
  - cluster
